version: "2"
services:
  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
        - "8000:8000"
  web:
    container_name: "web"
    build: .
    links:
      - db
    volumes:
    - "./src:/usr/src/app"
    ports:
      - 3000
  db:
    container_name: "db"
    build: ./db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATABASE=phillysms
    ports:
      - "5432:5432"
    volumes:
    - "postgres:/var/lib/psql/data"
  

volumes:
  web:
  postgres:
